### ISSUE TITLE
Hope for Toward-Human-Like-Grasp training code

### ISSUE THREAD

**Issue by lxhy9799** [zhutq-github/Toward-Human-Like-Grasp#2]
Hello
I recently noticed your work "Toward-Human-Like-Grasp", which has strong reference value for our current research work. Therefore, I hope to reproduce its. However, this work has not released the model  code, we hope to get  the code. We will refer to your paper in future articles. 
Thank you!

**Comment by zhutq-github** [comment]
你好，

非常感谢你的关注。我们的预期计划是进一步优化方法完成真实操作实验后再公开代码，但是疫情和繁复的实验设备准备工作拖延了整体进度。好在我们前段时间已经完成了实验，代码也会随着新工作公开。但是为了不影响你的进度，我可以整理一份简易的版本先传于你，可行吗？

再次感谢~

**Comment by lxhy9799** [comment]
你好，
     非常感谢你的回复。可行的。
祝好！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月16日 14:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [zhutq-github/Toward-Human-Like-Grasp] Hope for Toward-Human-Like-Grasp training code (Issue #2) |

你好，

非常感谢你的关注。我们的预期计划是进一步优化方法完成真实操作实验后再公开代码，但是疫情和繁复的实验设备准备工作拖延了整体进度。好在我们前段时间已经完成了实验，代码也会随着新工作公开。但是为了不影响你的进度，我可以整理一份简易的版本先传于你，可行吗？

再次感谢~

**Comment by RIP4KOBE** [comment]
> 你好，
> 
> 非常感谢你的关注。我们的预期计划是进一步优化方法完成真实操作实验后再公开代码，但是疫情和繁复的实验设备准备工作拖延了整体进度。好在我们前段时间已经完成了实验，代码也会随着新工作公开。但是为了不影响你的进度，我可以整理一份简易的版本先传于你，可行吗？
> 
> 再次感谢~

您好，

我对您"Toward Human-Like Grasp: Dexterous Grasping via Semantic Representation of Object-Hand"的这份工作也非常感兴趣，请问您的新工作和相应代码预计何时发布呢？可以也传送我一份简易版本的代码嘛？

祝好！

**Comment by kninad** [comment]
@zhutq-github I too would be interested in the code for this paper. Seems like this was accepted ~ 1 year back! Hence, a code release would be very helpful and perhaps necessary for spreading your research :)

**Comment by zhutq-github** [comment]
简版已上传，辛苦久等

**Comment by zhutq-github** [comment]
> @zhutq-github I too would be interested in the code for this paper. Seems like this was accepted ~ 1 year back! Hence, a code release would be very helpful and perhaps necessary for spreading your research :)

Code has been uploaded.

**Comment by zhutq-github** [comment]
> 

简版已上传，辛苦久等

**Comment by zhutq-github** [comment]
> Hello I recently noticed your work "Toward-Human-Like-Grasp", which has strong reference value for our current research work. Therefore, I hope to reproduce its. However, this work has not released the model code, we hope to get the code. We will refer to your paper in future articles. Thank you!

简版已上传，辛苦久等
