### ISSUE TITLE
运行python train_GraspNet.py报错

### ISSUE THREAD

**Issue by lululovecode** [zhutq-github/Toward-Human-Like-Grasp#3]
你好，报错如下：
(base)/Toward-Human-Like-Grasp$ python train_GraspNet.py
the chosen_chkp for pretrain_model is: None

Data Preparation
****************
./datasets/function_area
Traceback (most recent call last):
  File "/mnt/workspace/hl/Toward-Human-Like-Grasp/train_GraspNet.py", line 233, in <module>
    training_dataset = GraspNetDataset(config, mode='train')
  File "/mnt/workspace/hl/Toward-Human-Like-Grasp/datasets/GraspNet.py", line 49, in __init__
    raise ('The specified folder(object_label_dir) does not exist')
TypeError: exceptions must derive from BaseException

这是数据集路径问题吗？求解答，谢谢

**Comment by zhutq-github** [comment]
代码里设置的数据集存放路径不存在

**Comment by lululovecode** [comment]
> 代码里设置的数据集存放路径不存在

但是我就是按照您主页源码直接下载使用的，数据集是要另下吗？求解答，谢谢！

**Comment by zhutq-github** [comment]
不用另下。下载完代码，按照readme里面的把数据解压到相应文件夹就行，train_GraspNet.py里面预设了路径是./datasets/function_area。你这报错的是datasets/GraspNet.py的第49行，你可以debug看看为啥路径不对

**Comment by lululovecode** [comment]
> 不用另下。下载完代码，按照readme里面的把数据解压到相应文件夹就行，train_GraspNet.py里面预设了路径是./datasets/function_area。你这报错的是datasets/GraspNet.py的第49行，你可以debug看看为啥路径不对

**感谢解答！问题已解决。**
您readme里写的是'./datasets/functional_area/'
train_GraspNet.py里写的是./datasets/function_area
建议修改一下readme文件hhh
（看来还是得读源码找问题
